name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-csharp1:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies C#1
        run: dotnet restore
        working-directory: src
      - name: Build C#1
        run: dotnet build --no-restore
        working-directory: src
      - name: Test C#1
        run: dotnet test --no-build --verbosity normal
        working-directory: src
